name = "lingualive-realtime-translator"
compatibility_date = "2026-06-07"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "SESSION_KV"
id = "c4c6e1d7b1b241e2be88f39cf8cff915"
preview_id = "c4c6e1d7b1b241e2be88f39cf8cff915"
